cloudflare:
  default:
    # Default settings that apply to all zones unless overridden
    ssl: "full"
    min_tls_version: "1.2"
    http3: true
    rocket_loader: "off"
    brotli: "on"
    ipv6: "on"
    always_online: "on"
    automatic_https_rewrites: "on"
    opportunistic_encryption: "on"
    cache_level: "aggressive"
    browser_cache_ttl: 14400
    edge_cache_ttl: 31536000
    challenge_ttl: 3600

  zones:
    - id: "b441db6e139659910adc1155990213e2"
      domain: "freesubnet.com"
      # This zone inherits all settings from default except those explicitly defined here
      settings:
        ssl: "strict"
        min_tls_version: "1.3"  # Override the default for this zone

    - id: "50f3f9a9c13476185106ff4623757ca5"
      domain: "linuxwebservice.net"
      # This zone can inherit settings from default without overriding anything
      settings: {}
