cloudflare:
  api_token: "{{ secrets.CLOUDFLARE_API_TOKEN }}"
  zones:
    - id: "{{ secrets.CLOUDFLARE_ZONE1_ID }}"
      domain: "{{ secrets.CLOUDFLARE_ZONE1_FQDN }}"
      settings:
        enable_http3: true
        enable_hsts: true
        hsts_max_age: 31536000
        tls_min_version: "1.2"
        secure_ciphers: "ECDHE-RSA-AES128-GCM-SHA256"
        enable_ddos_protection: true
        enable_waf: true
        enable_dnssec: true
        enable_https_rewrites: false
        geo_blocking_enabled: false
        geo_blocking_countries: []
        custom_header_enabled: false
        custom_header_key: "X-Custom-Header"
        custom_header_value: "Configured by https://github.com/fabriziosalmi/flared"
        cache_level: "aggressive"
        browser_cache_ttl: 14400
        polish_mode: "lossless"
        rate_limit:
          requests_per_minute: 100
        firewall_rules:
          - action: "block"
            description: "Block traffic from specific country"
            filter: "ip.geoip.country eq 'CN'"
