cloudflare:
  api_token: "{{ secrets.CLOUDFLARE_API_TOKEN }}"
  zones:
    - id: "{{ secrets.CLOUDFLARE_ZONE1_ID }}"
      domain: "{{ secrets.CLOUDFLARE_ZONE1_FQDN }}"
      settings:
        # Free plan settings
        ssl: "full"  # Can be 'off', 'flexible', 'full', 'strict'
        min_tls_version: "1.2"  # Minimum TLS version
        ciphers: ["ECDHE-RSA-AES128-GCM-SHA256", "ECDHE-RSA-AES256-GCM-SHA384"]  # Cipher suites for TLS
        http3: true  # Enable HTTP/3 (only if available)

        # Free performance settings
        rocket_loader: "off"  # Rocket Loader (available for free)
        brotli: "on"  # Brotli compression (free plan)
        ipv6: "on"  # Enable IPv6 (available on all plans)
        always_online: "on"  # Enable Always Online (free plan)
        automatic_https_rewrites: "on"  # Automatic HTTPS rewrites (free plan)
        opportunistic_encryption: "on"  # Opportunistic encryption (free)

        # Free security settings
        browser_integrity_check: "on"  # Browser Integrity Check (free)
        challenge_ttl: 3600  # Challenge TTL in seconds

        # Caching settings (available on free plan)
        cache_level: "aggressive"
        browser_cache_ttl: 14400
        edge_cache_ttl: 31536000

    - id: "{{ secrets.CLOUDFLARE_ZONE2_ID }}"  # Second domain
      domain: "{{ secrets.CLOUDFLARE_ZONE2_FQDN }}"
      settings:
        ssl: "strict"  # For the second domain, stricter SSL mode
        min_tls_version: "1.3"  # Set to the highest TLS version
        cache_level: "bypass"
        rocket_loader: "on"  # Different settings for second domain
