name: Cloudflare Settings Automation

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  apply-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp pydantic cloudflare tenacity pyyaml

      - name: Set up environment variables
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE1_ID }}
          CLOUDFLARE_FQDN: ${{ secrets.CLOUDFLARE_ZONE1_FQDN }}
        run: echo "Environment variables set."

      - name: Run Cloudflare script
        run: python scripts/cloudflare.py --config config/cloudflare.yaml
